stylelint/vscode-stylelint

package.json

This updates the URLs from:
`https://github.com/thibaudcolas/vscode-stylelint`
to:
`https://github.com/stylelint/vscode-stylelint`

update URLS in package.json

---

lib/stylelint-vscode/test/test.js

refs https://github.com/stylelint/stylelint/pull/4237

Fixed a testcase that caused an error on CI

---

lib/stylelint-vscode/index.js
lib/stylelint-vscode/test/test.js

Fixed #29 
e.g. "No, it's self explanatory."

Fixed an issue where content was clears by autofix

---

CHANGELOG.md
package-lock.json
package.json

See https://github.com/stylelint/stylelint/issues/4598

chore: update stylelint to v13.2.0

---

.vscodeignore

From now on the changelog tab will be available within VSCode.
No, it's self explanatory.

Include CHANGELOG.md in releases

---

lib/stylelint-vscode/index.js
lib/stylelint-vscode/test/test.js

Close #68
e.g. "No, it's self-explanatory."

Fixed bug that if there are errors that cannot auto-fixable, autofix will not work.

---

README.md

docs: note extension is official, improve writing

---

.eslintignore
.prettierignore
.vscodeignore
package-lock.json
package.json

Resolves #216
Reduces packaged size from >7 mb to ~500-600 kb

Bundle extension using esbuild

---

package-lock.json
package.json
src/index.js
src/server.js
src/stylelint-vscode.js
test/workspace/config-basedir/__snapshots__/index.js.snap
test/workspace/config-file/__snapshots__/index.js.snap
test/workspace/ignore-disables/__snapshots__/index.js.snap
test/workspace/lint/__snapshots__/index.js.snap
test/workspace/report-invalid-scope-disables/__snapshots__/index.js.snap
test/workspace/report-needless-disables/__snapshots__/index.js.snap
test/workspace/resolve-local/__snapshots__/index.js.snap
test/workspace/rule-doc/__snapshots__/index.js.snap
test/workspace/stylelint-path/__snapshots__/index.js.snap
test/workspace/syntax/__snapshots__/index.js.snap
test/workspace/validate/__snapshots__/index.js.snap

vscode-languageserver/client 7.0.0
vscode-languageserver-types 3.16.0

chore: update language server/client packages

---

.github/workflows/linting.yml
CHANGELOG.md
README.md
cspell.config.js
package-lock.json
package.json
src/index.js
src/utils/lsp/__tests__/__snapshots__/create-disable-completion-item.js.snap
src/utils/lsp/__tests__/create-disable-completion-item.js
src/utils/packages/__tests__/global-path-resolver.js
src/utils/packages/stylelint-resolver.js
src/utils/stylelint/__tests__/get-disable-diagnostic-rule.js
src/utils/stylelint/build-stylelint-options.js
test/e2e/custom-syntax/__snapshots__/index.js.snap
test/e2e/custom-syntax/index.js
test/e2e/validate/__snapshots__/index.js.snap
test/e2e/validate/index.js
test/integration/stylelint-vscode/__snapshots__/test.js.snap
test/integration/stylelint-vscode/test.js
types/index.d.ts

test: add cspell, fix spelling where needed

---

package-lock.json
package.json
src/utils/__tests__/iterables.js
src/utils/iterables.js
src/utils/lsp/display-error.js

Try bumping `eslint-config-stylelint` from 14.0.0 to 15.0.0

Bump `eslint-config-stylelint` from 14.0.0 to 15.0.0

---

package.json

Closes #288
- Description updated to "Official Stylelint extension for Visual Studio Code"

Rebrand — Option C, update description, keep existing logo

---

src/server/modules/__tests__/__snapshots__/code-action.ts.snap
src/server/modules/code-action.ts

fix: code actions on save does not apply

---

package.json
src/extension/__tests__/extension.ts
src/extension/extension.ts
test/e2e/__tests__/restart.ts
test/e2e/setup.ts

Closes #332
Adds "Restart Stylelint Server" command to the extension.

feat: Add restart server command

---

test/e2e/__tests__/__snapshots__/code-actions.ts.snap
test/e2e/__tests__/code-actions.ts
test/e2e/setup.ts
test/e2e/workspace/code-actions/.vscode/settings.json

test: add code actions on save end-to-end test

---

src/extension/__tests__/__snapshots__/extension.ts.snap
src/extension/__tests__/extension.ts
src/extension/extension.ts

fix: de-nest globs used for watching config files

---

src/server/modules/__tests__/old-stylelint-warning.ts

None, as it's a ts error fix in v1.3 branch.

fix: ts error in v1.3 branch

---

.github/workflows/testing.yml

Set timeout and permissions for testing CI

---

.github/dependabot.yml

None.
This enables us to bump ESLint dependencies together.

Configure Dependabot for ESLint dependencies

---

CHANGELOG.md

None.
Ref https://github.com/stylelint/vscode-stylelint/compare/v1.3.0...main
Note: I have never performed releasing this extension yet, so feel free to comment if there are any mistakes. 🙏🏼

Prepare 1.4.0

---

CHANGELOG.md

Fix 1.4.0 release date

---

package-lock.json
package.json

chore(deps-dev): remove unnecessary `@typescript/lib-dom`

---

README.md

docs: remove unused linting CI badge

---

CHANGELOG.md
package-lock.json
package.json

None
The date stated in the changelog should indicate the date of the merge and release.

Prepare v1.5

---

.github/workflows/releasing.yml
RELEASE.md
package-lock.json
package.json

None.
This enables project maintainers to perform releases more easily.
Ref https://code.visualstudio.com/api/working-with-extensions/publishing-extension
Summary:
- Install [`@vscode/vsce`](https://github.com/Microsoft/vsce) as a dev dependency.
- Add a GitHub Actions workflow performing a release.
- Add a release guide for maintainers.
What do you think about the automation? If you approve this way, I'll register the secret for publishing.

Automate releasing

---

CHANGELOG.md

Ref https://github.com/stylelint/vscode-stylelint/compare/v1.5.0...main
---
I will try the new automated releasing introduced in #682.
See also https://github.com/stylelint/vscode-stylelint/blob/f78c6899b269f79516f61aacfcc3802250a31d6c/RELEASE.md

Prepare 1.5.1
