README.md

A slightly annoying follow up from my prior PR. I just found out that you can search for an extension with a specific ID - this'll avoid accidentally finding other extensions that keyword stuff their descriptions (which nothing does currently but whatever)

A slightly stricter install instruction

---

package.json
snippets/stylelint-disable.json
snippets/stylelint-disable.test.js

This pull request seeks to add the 3 available _stylelint-disable_ snippets
Support is added for CSS, PostCSS, and SCSS
• `/* stylelint-disable */`/`/* stylelint-enable */`
• `/* stylelint-disable-line */`
• `/* stylelint-disable-next-line rule */`

feat: Add `stylelint-disable` snippets

---

README.md

See #45 https://github.com/stylelint/vscode-stylelint/issues/45#issuecomment-586624419
e.g. "No, it's self explanatory."

Remove `editor.codeActionsOnSaveTimeout` reference

---

README.md
lib/stylelint-vscode/index.js
lib/stylelint-vscode/test/fake-stylelint.js
lib/stylelint-vscode/test/test.js
package.json
server.js
test/ws-stylelint-path-test/.vscode/settings.json
test/ws-stylelint-path-test/fake-stylelint.js
test/ws-stylelint-path-test/index.js
test/ws-stylelint-path-test/stylelint.config.js
test/ws-stylelint-path-test/test.css

Related to #44.
This PR adds `"stylelint.stylelintPath"` option.
The `stylelint.stylelintPath` option is similar to the [`prettier.prettierPath`](https://github.com/prettier/prettier-vscode#prettierprettierpath) option of `prettier-vscode`.
By setting the stylelint module path in the `stylelint.stylelintPath` option, the stylelint module selected by the user can be used with this extension.
The main purpose of the `stylelint.stylelintPath` option is to solve problems when used with Yarn 2. I tested CSS in the Yarn 2 environment and it worked.
However, it did not work with SCSS. This is probably another issue, as it did not work with the CLI. 
(I'm not familiar with Yarn, so my …

Add "stylelint.stylelintPath" option

---

package.json

This PR updates the _snippets_ extension config so that the _stylelint-disable_ disable snippets are also available with Less files

Include snippets for Less files

---

.vscodeignore

This PR fixes an isssue where the `/snippets` folder was not included in the  published extension:
`[2020-02-17 19:25:08.320] [renderer1] [error] Error: Unable to read file '/Users/netweb/.vscode/extensions/stylelint.vscode-stylelint-0.82.0/snippets/stylelint-disable.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/Users/netweb/.vscode/extensions/stylelint.vscode-stylelint-0.82.0/snippets/stylelint-disable.json')`

Add `snippets` folder to `.vscodeignore`

---

README.md
lib/stylelint-vscode/index.js
lib/stylelint-vscode/test/test.js
package.json
server.js
test/ws-report-needless-disables-test/.vscode/settings.json
test/ws-report-needless-disables-test/index.js
test/ws-report-needless-disables-test/stylelint.config.js
test/ws-report-needless-disables-test/test.css

Related to #38.
This PR adds the "stylelint.reportNeedlessDisables" option.
The "stylelint.reportNeedlessDisables" option is passed to the [`reportNeedlessDisables`] option in stylelint's Node.js API.
The result is displayed on the marker.
The output error supports quick fix.
[`reportNeedlessDisables`]: https://stylelint.io/user-guide/usage/options#reportneedlessdisables

Add "stylelint.reportNeedlessDisables" option

---

README.md
index.js
package.json
server.js
test/ws-basic-test/index.js
test/ws-lint-test/index.js
test/ws-lint-test/stylelint.config.js
test/ws-lint-test/test.css
test/ws-lint-test/test.md
test/ws-lint-test/test.scss
test/ws-validate-test/.vscode/settings.json
test/ws-validate-test/index.js
test/ws-validate-test/stylelint.config.js
test/ws-validate-test/test.css
test/ws-validate-test/test.md
test/ws-validate-test/test.scss

Closes #73
This PR adds "stylelint.validate" option.

Add "stylelint.validate" option

---

README.md
lib/stylelint-vscode/index.js
lib/stylelint-vscode/test/test.js
package-lock.json
package.json
server.js
test/ws-report-invalid-scope-disables-test/.vscode/settings.json
test/ws-report-invalid-scope-disables-test/index.js
test/ws-report-invalid-scope-disables-test/stylelint.config.js
test/ws-report-invalid-scope-disables-test/test.css

Related to #38.
This PR adds the "stylelint.reportInvalidScopeDisables" option.
The "stylelint.reportInvalidScopeDisables" option is passed to the [`reportInvalidScopeDisables`] option in stylelint's Node.js API.
The result is displayed on the marker.
The output error supports quick fix.
[`reportInvalidScopeDisables`]: https://stylelint.io/user-guide/usage/options#reportneedlessdisables

Add "stylelint.reportInvalidScopeDisables" option

---

README.md
package.json
server.js
test/ws-config-basedir-test/.vscode/settings.json
test/ws-config-basedir-test/config-basedir/stylelint-config1.js
test/ws-config-basedir-test/config-basedir/stylelint-config2.js
test/ws-config-basedir-test/index.js
test/ws-config-basedir-test/stylelint.config.js
test/ws-config-basedir-test/test.css

Related to #38.
This PR adds the `"stylelint.configBasedir"` option.
The `"stylelint.configBasedir"` option is passed to the `configBasedir` option in stylelint's Node.js API.

Add "stylelint.configBasedir" option

---

README.md
package.json
server.js
test/ws-ignore-disables-test/.vscode/settings.json
test/ws-ignore-disables-test/index.js
test/ws-ignore-disables-test/stylelint.config.js
test/ws-ignore-disables-test/test.css

Related to #38.
This PR adds the `"stylelint.ignoreDisables"` option.
The `"stylelint.ignoreDisables"` option is passed to the `ignoreDisables` option in stylelint's Node.js API.

Add "stylelint.ignoreDisables" option

---

README.md
package.json
server.js
test/utils.js
test/ws-config-basedir-test/index.js
test/ws-ignore-disables-test/index.js
test/ws-lint-test/index.js
test/ws-report-invalid-scope-disables-test/index.js
test/ws-report-needless-disables-test/index.js
test/ws-rule-doc-test/index.js
test/ws-stylelint-path-test/index.js
test/ws-syntax-test/.vscode/settings.json
test/ws-syntax-test/index.js
test/ws-syntax-test/stylelint.config.js
test/ws-syntax-test/test.css
test/ws-validate-test/index.js

Closes #38.  
**Note:** #38 can be closed if #117 and #118 are also merged.
This PR adds the `"stylelint.syntax"` option.
The `"stylelint.syntax"` option is passed to the `syntax` option in stylelint's Node.js API.

Add "stylelint.syntax" option

---

package-lock.json
package.json

Related to https://github.com/stylelint/vscode-stylelint/issues/120#issuecomment-640957765
- Change the version of `engines.vscode` from ">=1.41.0" to ">=1.43.0".
This version is a supported version of complex diagnostic codes. Use complex diagnostic codes in documentation links: #86
- Downgrade the version of `@types/vscode` from "^1.45.1" to "1.43.0"
Match the versions so that we can build.

Change the supported version of vscode to ">=1.43.0".

---

README.md
package.json
server.js
test/ws-config-file-test/.vscode/settings.json
test/ws-config-file-test/config-folder/stylelint.config.js
test/ws-config-file-test/index.js
test/ws-config-file-test/test.css

Closes #127
This PR adds the "stylelint.configFile" option.
The "stylelint.configFile" option is passed to the configFile option in stylelint's Node.js API.

Add stylelint.configFile option

---

README.md

Excited that we moved to GitHub Actions in #167! This PR just updates our status badges on the `README` to use the new actions, rather than the (now defunct) Travis CI build.

Update status badges for "Test", "Lint" actions

---

index.js
server.js
test/ws-formatter-test/.vscode/settings.json
test/ws-formatter-test/index.js
test/ws-formatter-test/test.expected.css
test/ws-formatter-test/test.input.css

Closes #25.
The language server has existing functionality checking when language IDs are removed from configuration (`connection.onDidChangeConfiguration`). This implementation adds a check for added language IDs and sends the client a notification when IDs are added or removed using the notification methods `stylelint/languageIdsAdded` and `stylelint/languageIdsRemoved`.
When the client receives these notifications, it registers or unregisters, as appropriate, a document formatting edit provider with VS Code for the given language IDs. When the provider is asked to provide formatting edits, it sends a `DocumentFormattingRequest` to the language server and returns the result. …

Add support for Format Document action

---

bundle.js
package.json

Fixes #237
The bundler cannot recognize the requires in the stylelint library for syntaxes, due to the lazy loads in the form `importLazy('package')` obscuring the require that is taking place.
This patch adds each syntax as its own entry point to bypass this limitation. It will no longer be necessary when targeting stylelint 14.
see: https://github.com/stylelint/stylelint/blob/13.13.1/lib/syntaxes/index.js

fix: add syntax entry points to fix lazy load bug

---

package-lock.json
package.json

Fixes #239
postcss-syntax uses require statements without string literals, so the bundler is unable to recognize the dependencies at bundle time. This fork uses static requires for packages used in vscode-stylelint to allow the proper resolution of packages.
This fix, along with the fix for #237, will no longer be required for 1.x of this extension, which will be tracking stylelint 14.
See https://github.com/adalinesimonian/postcss-syntax/commit/ba1d4a6

fix: use postcss-syntax fork until 1.x

---

src/utils/packages/stylelint-resolver.js

Don't assume `#logger` isn't available when `#connection` isn't.
See https://github.com/stylelint/vscode-stylelint/issues/281#issuecomment-953650843 for context

refactor: Check `this.#logger` separately

---

package-lock.json
package.json
src/start-server.js
src/utils/__tests__/errors.js
src/utils/errors.js
src/utils/logging/__tests__/error-formatter.js
src/utils/logging/error-formatter.js
src/utils/logging/index.js
types/index.d.ts

Encountered in #281 
Prior to this fix, in certain instances, logged errors would be missing critical information, such as `message` or `stack`.
Example, prior to fix:
```
[Debug - 9:24:33 a.m.] [language-server] Log message | error: {}
```
Example, after fix:
```
[Debug - 9:24:33 a.m.] [language-server] Log message | error: {"name":"Error","message":"…","stack":"…"}
```

fix: properly serialize errors sent to logger

---

src/utils/stylelint/__tests__/__snapshots__/process-linter-result.ts.snap
src/utils/stylelint/__tests__/__snapshots__/stylelint-runner.ts.snap
src/utils/stylelint/__tests__/__snapshots__/warning-to-diagnostic.ts.snap
src/utils/stylelint/warning-to-diagnostic.ts
test/e2e/__tests__/__snapshots__/config-basedir.ts.snap
test/e2e/__tests__/__snapshots__/config-file.ts.snap
test/e2e/__tests__/__snapshots__/ignore-disables.ts.snap
test/e2e/__tests__/__snapshots__/lint.ts.snap
test/e2e/__tests__/__snapshots__/report-invalid-scope-disables.ts.snap
test/e2e/__tests__/__snapshots__/report-needless-disables.ts.snap
test/e2e/__tests__/__snapshots__/stylelint-resolution.ts.snap
test/e2e/__tests__/__snapshots__/validate.ts.snap
test/integration/stylelint-vscode/__snapshots__/test.ts.snap

Fixes #323
Adjusts diagnostic creation to send [start, end) ranges instead of [start, end]. Works around VS Code's inconsistent behaviour in which problems that are displayed for a single character may have a smaller hover region than the underline visual.

fix: make hovering over problems more reliable

---

src/server/modules/__tests__/old-stylelint-warning.ts
src/server/modules/old-stylelint-warning.ts

Closes #333 
Does not warn if Stylelint was resolved globally, only locally.

feat: Warn for old Stylelint regardless of language ID

---

package-lock.json
package.json
test/e2e/jest-runner-vscode.config.js

> See https://github.com/adalinesimonian/jest-runner-vscode/releases/tag/v2.1.0
The new version of jest-runner-vscode uses IPC for better test reporting and less lag when tests fail.

chore: update jest-runner-vscode to 2.1.0

---

.github/workflows/testing.yml

See https://github.com/stylelint/stylelint/pull/5874 and https://github.com/npm/cli/issues/4341

ci: downgrade npm to 8.3 as workaround

---

package-lock.json
package.json
src/utils/stylelint/__tests__/__snapshots__/process-linter-result.ts.snap
src/utils/stylelint/__tests__/__snapshots__/stylelint-runner.ts.snap
src/utils/stylelint/__tests__/__snapshots__/warning-to-diagnostic.ts.snap
src/utils/stylelint/__tests__/warning-to-diagnostic.ts
src/utils/stylelint/warning-to-diagnostic.ts
test/e2e/__tests__/__snapshots__/code-actions.ts.snap
test/e2e/__tests__/__snapshots__/config-basedir.ts.snap
test/e2e/__tests__/__snapshots__/config-file.ts.snap
test/e2e/__tests__/__snapshots__/ignore-disables.ts.snap
test/e2e/__tests__/__snapshots__/lint.ts.snap
test/e2e/__tests__/__snapshots__/validate.ts.snap
test/integration/stylelint-vscode/__snapshots__/test.ts.snap

Closes stylelint/vscode-stylelint#377
Since Stylelint 14.3.0, `meta.url` has been added:
<https://github.com/stylelint/stylelint/blob/14.3.0/CHANGELOG.md#1430>
Also, this change updates the `stylelint` package via `npm i stylelint`.

fix: fix rule doc URL

---

src/utils/stylelint/__tests__/formatting-options-to-rules.ts
src/utils/stylelint/formatting-options-to-rules.ts

Closes #398
"No, it's self-explanatory."

fix: don't pass invalid "false" rule value when formatting

---

.github/ISSUE_TEMPLATE/bug.yml

None.
This PR updates the bug issue template to require a reproduction repository to be provided.
Many of the currently open issues are not reproducible as no repositories have been provided to reproduce the issue.

chore: update bug issue template

---

README.md

Current URL (https://stylelint.io/user-guide/configuration) returns error 404. I think that https://stylelint.io/user-guide/configure is the good one.

docs: fix "stylelint configuration file" link

---

README.md

Whilst looking at the extension page of another VSCode extension I noticed that this extension included their Open Collective sponsors in the readme, I think we should do the same, so here's a PR doing just that copied from the main Stylelint repo
None, as it's a documentation tweak

Add VSCode Stylelint Contributors, Sponsors, and Backers

---

package-lock.json
package.json

Reverts stylelint/vscode-stylelint#412
This update seemed to be the cause of the currently falling tests. I don't remember if the CI for this PR passed at that time 😓

Revert "chore(deps-dev): bump @vscode/test-electron from 1.6.2 to 2.1.5"

---

README.md
package.json
src/server/__tests__/__snapshots__/server.ts.snap
src/server/server.ts
src/server/types.ts
src/utils/documents/__tests__/get-fixes.ts
src/utils/stylelint/__tests__/__snapshots__/stylelint-runner.ts.snap
src/utils/stylelint/__tests__/build-stylelint-options.ts
src/utils/stylelint/build-stylelint-options.ts
src/utils/stylelint/types.ts
test/e2e/__tests__/__snapshots__/report-descriptionless-disables.ts.snap
test/e2e/__tests__/report-descriptionless-disables.ts
test/e2e/workspace/descriptionless-disables/.vscode/settings.json
test/e2e/workspace/descriptionless-disables/stylelint.config.js
test/e2e/workspace/descriptionless-disables/test.css
test/e2e/workspace/workspace.code-workspace
test/integration/stylelint-vscode/__snapshots__/test.ts.snap
test/integration/stylelint-vscode/test.ts
test/unit/server-mocks.ts

Closes #441
Did in a way similar to other options, adding similar tests, adding it to the integration ones, and testing via running an extension development host:

Add "stylelint.reportDescriptionlessDisables" option

---

package.json

You can have the Sponsor badge appear in the header on the marketplace. Example here: marketplace.visualstudio.com/items?itemName=HTMLHint.vscode-htmlhint.
To add that to the extension you just need to add this to the extension's package.json
```json
"sponsor": {
"url": "https://opencollective.com/stylelint"
}
```
Partial fix for #433

Add Sponsor badge to extension

---

src/server/modules/__tests__/formatter.ts

Fix copied from original PR
https://github.com/stylelint/vscode-stylelint/pull/426/files#diff-f2680deb1906c0920d4e4b4f73879a32a741ed4288aabb2a218a2eef48f38211
Just trying to see if we can help push [feat: Report ranges for diagnostics](https://github.com/stylelint/vscode-stylelint/pull/358) through the finishing line
We tested the branch and it worked nicely!
| Before | After | 
| --- | --- |
| ![Screenshot 2023-03-28 at 16 54 52](https://user-images.githubusercontent.com/905006/228304703-85ec2421-6fdb-4b9e-ba41-86cda320319b.png) | ![Screenshot 2023-03-28 at 16 55 21](https://user-images.githubusercontent.com/905006/228304707-31880cab-4b84-4e5d-9429-abf69ee13aa0.png) |
Even though CI seemed green in the PR, some tests appeared to be failing locally. We just went ahead and borrowed from …

Fixes server/modules/formatter tests

---

README.md

See https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto
- `explicit` is the same as `true`
- `never` is the same as `false`

docs: fix `editor.codeActionsOnSave` values in README examples

---

.github/workflows/testing.yml

None.
- Use `cache: npm` of `actions/setup-node` instead of `actions/cache`
- Install the old npm version only on Node.js 14 and Windows
- Remove the useless `env.CI`, which is set by default

ci: improve testing

---

.github/dependabot.yml

Closes #429
We have to bump Jest-related packages at the same time, especially for major updates.
Also, this PR will reduce the number of Dependabot PRs.
---
We can see the related dependencies in `package.json` as below:
```sh-session
$ git grep 'jest' package.json
package.json:225:    "@types/jest": "^27.0.3",
package.json:240:    "jest": "^27.4.3",
package.json:241:    "jest-runner-vscode": "^2.1.0",
package.json:253:    "ts-jest": "^27.0.7",
package.json:275:    "test": "npm run build-bundle && jest",
package.json:276:    "test:e2e": "npm run build-bundle && jest --projects test/e2e",
package.json:277:    "test:integration": "jest --projects test/integration", …
```

Configure Dependabot for Jest dependencies

---

.github/workflows/codeql.yml

None.
- Set new language `javascript-typescript`
(see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#changing-the-languages-that-are-analyzed)
- Remove useless Node.js setup

ci: improve CodeQL workflow

---

package.json

None
This brings the default configuration for `stylelint.validate` in line with [the readme](https://github.com/stylelint/vscode-stylelint#:~:text=In%20current%20versions%20of%20the%20extension%2C%20the%20extension%20only%20supports%20validating%20CSS%20and%20PostCSS%20out%20of%20the%20box), which states:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"In current versions of the extension, the extension only supports validating CSS and PostCSS out of the box"
Should `"less"` also be removed from the default value for `stylelint.snippet`? I have now added a commit to do that, based on the history below.
**History:**
- First removed in [`a4e0454`](https://github.com/stylelint/vscode-stylelint/commi …

Remove "less" from defaults

---

src/extension/extension.ts

This change doesn't use `require.resolve()` to prevent the build warning below:
```sh-session
$ npm run bundle
> vscode-stylelint@1.3.0 bundle
> npm run bundle-base -- --sourcemap
> vscode-stylelint@1.3.0 bundle-base
> ts-node --transpile-only -P tsconfig.scripts.json scripts/bundle.ts --sourcemap
▲ [WARNING] "./start-server" should be marked as external for use with "require.resolve"
build/extension/extension.js:13:39:
13 │     const serverPath = require.resolve('./start-server');
╵                                        ~~~~~~~~~~~~~~~~
1 warning
```
None.

Fix build warning for `require.resolve()`

---

.github/dependabot.yml

See #584
This project is not yet ready for ESLint v9. For example, see #584.

chore(deps-dev): exclude `eslint` from Dependabot group updates

---

package-lock.json
package.json

None.
Ref https://github.com/microsoft/TypeScript/releases
Dependabot doesn't create a PR to bump it for some reason.

chore(deps-dev): bump typescript from 4.9.5 to 5.5.4

---

test/e2e/__tests__/custom-syntax.ts
test/e2e/helpers.ts
test/e2e/workspace/custom-syntax/custom-syntax.js
test/e2e/workspace/custom-syntax/test.scss

None.
The current E2E test often fails with the `stylelint.customSyntax` case. E.g.
```
"stylelint.customSyntax" setting
[main 2025-03-06T15:39:38.577Z] CodeWindow: renderer process gone (reason: crashed, code: -36861)
[main 2025-03-06T15:39:38.603Z] Extension host with pid 2176 exited with code: 0, signal: unknown.
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
at s.send (node:electron/js2c/browser_init:2:93948)
at _.send (node:electron/js2c/browser_init:2:79174)
```
https://github.com/stylelint/vscode-stylelint/actions/runs/13701322508/job/38319300464#step:11:57
I'm still unsure why, but I found that replacing …

Fix flaky E2E test

---

package-lock.json
package.json
test/e2e/helpers.ts

May potentially fix e2e test flakiness observed in https://github.com/stylelint/vscode-stylelint/actions/runs/13701322508. An update is nonetheless due. Will likely need to update to a newer version than 1.83, but that may require changes to tests, so this is a stepping stone.

chore: bump oldest supported vscode to 1.83.0

---

.eslintrc.js
.github/workflows/testing.yml
.vscode-test.js
package.json
test/e2e/__tests__/stylelint-resolution.ts
test/e2e/pnp/__tests__/stylelint-resolution.ts

Follow-up to #643
This PR will separate the PnP test process, stabilizing the tests.
I will revert the other test stabilization changes.
It seems that the PnP tests apply patches to the Node filesystem, which can break other tests.
Presumably the user can just restart the extension and the problem will go away, but this doesn't work within the tests, and the error appears to occur before the extension can be restarted.

Separate PnP test process

---

src/extension/__tests__/__snapshots__/extension.ts.snap
src/extension/__tests__/extension.ts
src/extension/extension.ts

Closes #647 
I split `stylelint.config.{js,cjs,mjs}` and `.stylelintignore` into separate watchers for readability and to avoid nested brackets.

fix: add file watchers for .mjs and .cjs configs

---

.github/workflows/testing.yml

Speeds up test runs especially when updating batches of dependencies. Computes the cache key based only off relevant dependencies/vscode engine version in package.json.

chore: invalidate vs code binary cache less often

---

package.json
scripts/run-e2e.js

Ensures that the workspace file is always formatted even if e2e tests failed, all while allowing for arguments to the test:e2e script to be passed to vscode-test, which is what is most often desired, rather than to the prettier cleanup script at the end. Uses the exit code of vscode-test as the exit code for the e2e script.

test: improve e2e run script

---

package-lock.json
package.json
test/e2e/workspace/code-actions/stylelint.config.js
test/integration/stylelint-vscode/__snapshots__/test.ts.snap
test/integration/stylelint-vscode/no-unknown.config.js
test/integration/stylelint-vscode/test.ts

This may resolve the CI failures in PR #721.
This replaces the deprecated package for CSS-in-JS syntax.
The removed package may not work with the latest Stylelint 16.24.0.
Ref:
- https://www.npmjs.com/package/@stylelint/postcss-css-in-js
- https://www.npmjs.com/package/postcss-styled-syntax

Replace deprecated `@stylelint/postcss-css-in-js` with `postcss-styled-syntax`
